![Q-learning](qlearning.png)

In [345]:
import gym
import random
import numpy as np
from collections import deque
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [4]:
env = gym.make('CartPole-v1')
env.reset()

array([ 0.02208477, -0.04599441,  0.04966537, -0.01883407])

In [3]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[-0.03409489 -0.01150015  0.043099    0.02441809]
[-0.0343249   0.18297807  0.04358736 -0.25436116]
[-0.03066534  0.37745144  0.03850014 -0.53298353]
[-0.02311631  0.57201136  0.02784047 -0.81329091]
[-0.01167608  0.76674117  0.01157465 -1.09708839]
[ 0.00365874  0.96170882 -0.01036712 -1.3861174 ]
[ 0.02289292  0.76671764 -0.03808947 -1.09669422]
[ 0.03822727  0.57211738 -0.06002335 -0.81620116]
[ 0.04966962  0.76800752 -0.07634738 -1.12714348]
[ 0.06502977  0.96404217 -0.09889025 -1.4427632 ]
[ 0.08431061  0.77026693 -0.12774551 -1.18254678]
[ 0.09971595  0.57701287 -0.15139645 -0.93248286]
[ 0.11125621  0.38422207 -0.1700461  -0.69094525]
[ 0.11894065  0.19181645 -0.18386501 -0.4562524 ]
[ 0.12277698 -0.00029489 -0.19299006 -0.22669487]
[ 0.12277108 -0.19221035 -0.19752395 -0.00055352]
[ 0.11892688 -0.3840321  -0.19753502  0.22388912]
[ 0.11124623 -0.57586322 -0.19305724  0.44834172]
[ 0.09972897 -0.76780537 -0.18409041  0.67449927]
[ 0.08437286 -0.57066713 -0.17060042  0.32997103]


[ 0.03788316  0.20256632  0.03768829 -0.32919504]
[ 0.04193449  0.00692869  0.03110438 -0.02486924]
[ 0.04207307  0.20159108  0.030607   -0.30757839]
[ 0.04610489  0.00604668  0.02445543 -0.00540211]
[ 0.04622582 -0.1894173   0.02434739  0.29489538]
[0.04243747 0.00534923 0.0302453  0.00998959]
[ 0.04254446 -0.19019313  0.03044509  0.31205975]
[ 0.0387406  -0.38573529  0.03668628  0.61418653]
[ 0.03102589 -0.19114466  0.04897002  0.33328034]
[0.027203   0.00324733 0.05563562 0.05643333]
[ 0.02726794  0.19752925  0.05676429 -0.2181902 ]
[ 0.03121853  0.39179575  0.05240048 -0.49244086]
[ 0.03905444  0.19597537  0.04255167 -0.18371478]
[0.04297395 0.00027122 0.03887737 0.12208215]
[ 0.04297938 -0.19538554  0.04131901  0.42677258]
[ 0.03907166 -0.39106762  0.04985447  0.73218951]
[ 0.03125031 -0.19666873  0.06449826  0.45560463]
[ 0.02731694 -0.3926405   0.07361035  0.76790039]
[ 0.01946413 -0.58869442  0.08896836  1.08280681]
[ 0.00769024 -0.78487063  0.11062449  1.40202949]
[-0.00800717

[ 0.01260002  0.23434308  0.02744103 -0.25330434]
[ 0.01728688  0.42906268  0.02237494 -0.53720712]
[ 0.02586813  0.62386301  0.0116308  -0.8227568 ]
[ 0.03834539  0.81882393 -0.00482433 -1.11175901]
[ 0.05472187  1.01400892 -0.02705951 -1.40595143]
[ 0.07500205  1.2094561  -0.05517854 -1.70696942]
[ 0.09919117  1.40516746 -0.08931793 -2.01630392]
[ 0.12729452  1.6010957  -0.12964401 -2.33524933]
[ 0.15931643  1.40736137 -0.176349   -2.08509523]
Episode finished after 12 timesteps
[-0.04661579  0.01678409 -0.02231401 -0.02875736]
[-0.0462801  -0.17801087 -0.02288915  0.25680257]
[-0.04984032 -0.37279868 -0.0177531   0.54217892]
[-0.0572963  -0.17743177 -0.00690953  0.2439556 ]
[-0.06084493 -0.37245436 -0.00203041  0.53445111]
[-0.06829402 -0.56754769  0.00865861  0.82649357]
[-0.07964497 -0.76278698  0.02518848  1.12188712]
[-0.09490071 -0.95823002  0.04762622  1.42236331]
[-0.11406531 -1.15390754  0.07607349  1.7295436 ]
[-0.13714346 -0.95973266  0.11066436  1.4614677 ]
[-0.15633812 -

In [4]:
print(env.action_space)
# 0: 1 unit of force in left direction
# 1: 1 unit of force in right direction

Discrete(2)


In [5]:
print(env.observation_space)
# 0: Cart position
# 1: Cart velocity
# 2: Pole angle
# 3: Pole velocity at tip

Box(4,)


# Cartpole domain

In [10]:
env.action_space.n

2

In [6]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [7]:
env.observation_space.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

The input space is 4 dimensional and continuous.
* Cart position: $x: \in [-4.8, 4.8]$
* Cart velocity: $x' \in [-3.4*10^{38}, 3.4*10^{38}]$
* Angle: $\theta \in [-0.42, 0.42]$
* Angle velocity: $\theta' \in [-3.4*10^{38}, 3.4*10^{38}]$

# Q-learning parameters
* $\alpha$: Learning rate - Used to smooth the updates and make them less radical, which prevents errors caused by noise.
* $\epsilon$: Exploration rate - Regulates between explotation and exploration. Instead of picking the best action in a state, which a probability of $\epsilon$ a random action is picked. This should prevent the algorithm from getting stuck at a local minima (e.g. if a bad choice was made in the beginning, without $\epsilon$ the agent would never discover any other, potentially better, path.
* $\gamma$: Discount factor - Used to penalize the agent if it takes long to reach its goal. However in this case we set gamma to 1 since it is our goal to survive as long as possible.

In [337]:
np.repeat(1, 100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [445]:
np.reshape([1, 2, 3, 4], [1, 4])

array([[1, 2, 3, 4]])

In [451]:
class QSolver():
    def __init__(self, env, eps, alpha, gamma, batch_size = 5000, memory_size=1000000):
        self.env = env
        self.eps = eps
        self.alpha = alpha
        self.gamma = gamma
        self.memory = deque(maxlen=memory_size)
        self.batch_size = batch_size
        
        
        self.model = Sequential()
        self.model.add(Dense(24, input_shape=(self.env.observation_space.shape[0],), activation="relu"))
        self.model.add(Dense(24, activation="relu"))
        self.model.add(Dense(self.env.action_space.n, activation="linear"))
        self.model.compile(loss="mse", optimizer=Adam(lr=0.02))        

#         # Random Forest
#         self.model = RandomForestRegressor()
        
#         # Initiate Model
#         X = np.random.random_sample((100, 5))
#         y = np.repeat(1, 100)
#         self.model.fit(X, y)
        
        ## Linear Model
        #self.model = LinearRegression()

        # Initiate Model Parameters
        #self.model.intercept_ = 0
        #self.model.coef_ = np.zeros(self.env.observation_space.shape[0] + 1)

    def remember(self, state, action, newReward, newState, terminated):
        self.memory.append((state, action, newReward, newState, terminated))

#     def feature_matrix(self, state):
#         return np.array([list(state) + [0],
#                         list(state) + [1]])

    def greedy_action(self, state):
#         X = self.feature_matrix(state)
        q_values = self.model.predict(state)
        return np.argmax(q_values[0])
    
    def epsilon_greedy(self, state):
        if np.random.random() >= self.eps:
            return self.greedy_action(state)
        
        return self.env.action_space.sample()

    def experience_replay(self):
        if len(self.memory) < self.batch_size:
            return
        batch = random.sample(self.memory, self.batch_size)
#         target_q_values = []
#         X_list = []
        for state, action, newReward, newState, terminated in batch:
            q_update = newReward
            if not terminated:
#                 X_next = self.feature_matrix(newState)
                q_update = (newReward + self.gamma * np.amax(self.model.predict(newState)[0]))
#             x = self.feature_matrix(state)[action]
#             X_list.append(x)
            q_value = self.model.predict(state)[0][action]
            q_value = (1-self.alpha)*q_value + self.alpha*q_update
            print(f"state {np.array(state[0]).shape}")
            print(f"q_value: {q_value}")
            
#             target_q_values.append(q_value)
            self.model.fit(np.array(state[0]), q_value, verbose=0)

#         X = np.array(X_list)
#         target_q_values = np.array(target_q_values)
        
        # Updating value function parameters
        #print(f"X.shape: {X.shape}, target_q_values.shape: {target_q_values.shape}")
#         self.model.fit(X, target_q_values)
                
    def step(self, action):
        return self.env.step(action)
        
    def run_episode(self, render=False, exposition=False):
        state = self.env.reset()
        state = np.reshape(state, [1, self.env.observation_space.shape[0]])
        
        t = 0
        while True:
            t += 1
            
            if render:
                self.env.render()
                
            if exposition:
                action = self.greedy_action(state)
            else:
                action = self.epsilon_greedy(state)
                
            newState, newReward, terminated, info = self.env.step(action)
            newState = np.reshape(newState, [1, self.env.observation_space.shape[0]])
            
            if  not exposition:
                # Add to memory
                self.remember(state, action, newReward, newState, terminated)

                # Update Model
                self.experience_replay()

#             if not exposition:
#                 self.update_Q(state, action, newReward, newState)

            # Update state
            print(f"state {state}")
            print(f"newState {newState}")
            state = newState

            if terminated:
                print(f"Episode length: {t}")
                break
                
        self.env.close()
        
    def run_q_learning(self, n_episodes, render=False):

        for t in range(n_episodes):
#            old_params = self.model.coef_.copy()
            print(f"Episode: {t+1}")
            self.run_episode()
                        
#             if len(self.memory) > self.batch_size and np.allclose(old_params, self.model.coef_,  0.05):
#                 print(f'Learning Converged. Parameters: {self.model.coef_}')
#                 break
            
#            self.eps = 1/(t+1)

In [452]:
class DiscreteQSolver(QSolver):
    def __init__(self, env, eps, alpha, gamma, bucket_sizes=(7, 13, 7, 13)):
        QSolver.__init__(self, env, eps, alpha, gamma)
        self.bucket_sizes = bucket_sizes
        self.Q = np.zeros(bucket_sizes + (self.env.action_space.n,))
        
    def greedy_action(self, state):
        state_discrete = self.discretize(state, self.env.observation_space)
        return np.argmax(self.Q[tuple(state_discrete)])
    
    def step(self, action):
        observation, reward, done, info = self.env.step(action)
        return discretize(observation), reward, done, info
    
    def update_Q(self, state, action, newReward, newState):
        state_discrete = self.discretize(state.copy(), self.env.observation_space)
        newState_discrete = self.discretize(newState.copy(), self.env.observation_space)
        
        greedy_action = self.greedy_action(newState_discrete)
        q_greedy_action = self.Q[tuple(state_discrete)][greedy_action]
        self.Q[tuple(state_discrete)][action] + self.alpha * (newReward + self.gamma * q_greedy_action - self.Q[tuple(state_discrete)][action])     
        
    def discretize(self, obs, obs_space):
        bucket_arrays = [np.linspace(obs_space.low[i], obs_space.high[i], self.bucket_sizes[i]) for i, x in enumerate(obs)]
        state_space = [np.digitize(obs[i], bucket_arrays[i]) for i, x in enumerate(obs)]
        return np.array(state_space).ravel()-1

In [453]:
eps = 0.9
alpha = 0.05
gamma = 0.5
solver = DiscreteQSolver(env, eps, alpha, gamma)

In [454]:
eps = 0.5
alpha = 0.05
gamma = 0.95
solver = QSolver(env, eps, alpha, gamma)

In [450]:
solver.run_q_learning(n_episodes=1000)

Episode: 1
state [[-0.02006016 -0.00090834  0.00148681  0.01520851]]
newState [[-0.02007833  0.19419226  0.00179098 -0.27700494]]
state [[-0.02007833  0.19419226  0.00179098 -0.27700494]]
newState [[-0.01619448 -0.0009552  -0.00374912  0.01624233]]
state [[-0.01619448 -0.0009552  -0.00374912  0.01624233]]
newState [[-0.01621359  0.19422032 -0.00342427 -0.27762113]]
state [[-0.01621359  0.19422032 -0.00342427 -0.27762113]]
newState [[-0.01232918  0.38939095 -0.00897669 -0.5713821 ]]
state [[-0.01232918  0.38939095 -0.00897669 -0.5713821 ]]
newState [[-0.00454136  0.58463763 -0.02040434 -0.86687942]]
state [[-0.00454136  0.58463763 -0.02040434 -0.86687942]]
newState [[ 0.00715139  0.78003121 -0.03774192 -1.16590725]]
state [[ 0.00715139  0.78003121 -0.03774192 -1.16590725]]
newState [[ 0.02275201  0.97562351 -0.06106007 -1.47018025]]
state [[ 0.02275201  0.97562351 -0.06106007 -1.47018025]]
newState [[ 0.04226448  1.17143695 -0.09046367 -1.78129354]]
state [[ 0.04226448  1.17143695 -0.09

state [[ 0.10656496  0.81610574 -0.07088089 -1.19181432]]
newState [[ 0.12288707  0.62197002 -0.09471717 -0.9221635 ]]
state [[ 0.12288707  0.62197002 -0.09471717 -0.9221635 ]]
newState [[ 0.13532647  0.81823533 -0.11316044 -1.24304711]]
state [[ 0.13532647  0.81823533 -0.11316044 -1.24304711]]
newState [[ 0.15169118  0.62473276 -0.13802139 -0.98784787]]
state [[ 0.15169118  0.62473276 -0.13802139 -0.98784787]]
newState [[ 0.16418583  0.82140571 -0.15777834 -1.32050137]]
state [[ 0.16418583  0.82140571 -0.15777834 -1.32050137]]
newState [[ 0.18061395  1.01813039 -0.18418837 -1.65811768]]
state [[ 0.18061395  1.01813039 -0.18418837 -1.65811768]]
newState [[ 0.20097656  0.82557199 -0.21735072 -1.42801141]]
Episode length: 14
Episode: 19
state [[0.00816991 0.0267561  0.02623946 0.0203001 ]]
newState [[ 0.00870503  0.22149211  0.02664546 -0.26398985]]
state [[ 0.00870503  0.22149211  0.02664546 -0.26398985]]
newState [[ 0.01313487  0.41622381  0.02136566 -0.54815087]]
state [[ 0.01313487  

state [[ 0.01692432  0.34525219 -0.06527358 -0.67613538]]
newState [[ 0.02382936  0.5412175  -0.07879628 -0.98863418]]
state [[ 0.02382936  0.5412175  -0.07879628 -0.98863418]]
newState [[ 0.03465371  0.34723382 -0.09856897 -0.72170364]]
state [[ 0.03465371  0.34723382 -0.09856897 -0.72170364]]
newState [[ 0.04159839  0.54357112 -0.11300304 -1.04371244]]
state [[ 0.04159839  0.54357112 -0.11300304 -1.04371244]]
newState [[ 0.05246981  0.35011618 -0.13387729 -0.78853307]]
state [[ 0.05246981  0.35011618 -0.13387729 -0.78853307]]
newState [[ 0.05947213  0.15706207 -0.14964795 -0.54078558]]
state [[ 0.05947213  0.15706207 -0.14964795 -0.54078558]]
newState [[ 0.06261337  0.35393556 -0.16046366 -0.87662778]]
state [[ 0.06261337  0.35393556 -0.16046366 -0.87662778]]
newState [[ 0.06969209  0.1613156  -0.17799622 -0.63838376]]
state [[ 0.06969209  0.1613156  -0.17799622 -0.63838376]]
newState [[ 0.0729184  -0.0309366  -0.19076389 -0.4066167 ]]
state [[ 0.0729184  -0.0309366  -0.19076389 -0.4

state [[ 0.00793581  0.14732588  0.03498553 -0.3010746 ]]
newState [[ 0.01088232  0.34193216  0.02896404 -0.58252175]]
state [[ 0.01088232  0.34193216  0.02896404 -0.58252175]]
newState [[ 0.01772097  0.5366366   0.01731361 -0.86594167]]
state [[ 0.01772097  0.5366366   0.01731361 -0.86594167]]
newState [[ 2.84536998e-02  3.41283345e-01 -5.22600509e-06 -5.67865763e-01]]
state [[ 2.84536998e-02  3.41283345e-01 -5.22600509e-06 -5.67865763e-01]]
newState [[ 0.03527937  0.53640537 -0.01136254 -0.86055034]]
state [[ 0.03527937  0.53640537 -0.01136254 -0.86055034]]
newState [[ 0.04600747  0.73168021 -0.02857355 -1.1567842 ]]
state [[ 0.04600747  0.73168021 -0.02857355 -1.1567842 ]]
newState [[ 0.06064108  0.92716275 -0.05170923 -1.4582878 ]]
state [[ 0.06064108  0.92716275 -0.05170923 -1.4582878 ]]
newState [[ 0.07918433  1.12287947 -0.08087499 -1.76666623]]
state [[ 0.07918433  1.12287947 -0.08087499 -1.76666623]]
newState [[ 0.10164192  1.31881668 -0.11620831 -2.0833627 ]]
state [[ 0.10164

state [[ 0.09920772  1.31452322 -0.05072774 -1.90410528]]
newState [[ 0.12549818  1.51015527 -0.08880985 -2.21208343]]
state [[ 0.12549818  1.51015527 -0.08880985 -2.21208343]]
newState [[ 0.15570129  1.70600805 -0.13305151 -2.5307806 ]]
state [[ 0.15570129  1.70600805 -0.13305151 -2.5307806 ]]
newState [[ 0.18982145  1.51219245 -0.18366713 -2.28162853]]
state [[ 0.18982145  1.51219245 -0.18366713 -2.28162853]]
newState [[ 0.2200653   1.70848295 -0.2292997  -2.62480709]]
Episode length: 13
Episode: 82
state [[ 0.01294965 -0.01748779 -0.02803705  0.0429786 ]]
newState [[ 0.01259989  0.17802475 -0.02717748 -0.25841677]]
state [[ 0.01259989  0.17802475 -0.02717748 -0.25841677]]
newState [[ 0.01616039  0.37352394 -0.03234581 -0.55954646]]
state [[ 0.01616039  0.37352394 -0.03234581 -0.55954646]]
newState [[ 0.02363087  0.56908461 -0.04353674 -0.86224203]]
state [[ 0.02363087  0.56908461 -0.04353674 -0.86224203]]
newState [[ 0.03501256  0.76477146 -0.06078158 -1.16828992]]
state [[ 0.035012

state [[-0.0660855  -0.94889966  0.13871192  1.65193942]]
newState [[-0.08506349 -0.75564384  0.17175071  1.4054907 ]]
state [[-0.08506349 -0.75564384  0.17175071  1.4054907 ]]
newState [[-0.10017637 -0.56301921  0.19986052  1.17105168]]
state [[-0.10017637 -0.56301921  0.19986052  1.17105168]]
newState [[-0.11143675 -0.37097607  0.22328156  0.94708971]]
Episode length: 14
Episode: 108
state [[-0.02470224 -0.02828397  0.03800945  0.03566404]]
newState [[-0.02526792  0.16627288  0.03872274 -0.24478837]]
state [[-0.02526792  0.16627288  0.03872274 -0.24478837]]
newState [[-0.02194246  0.36082098  0.03382697 -0.52501011]]
state [[-0.02194246  0.36082098  0.03382697 -0.52501011]]
newState [[-0.01472604  0.55545097  0.02332677 -0.80684486]]
state [[-0.01472604  0.55545097  0.02332677 -0.80684486]]
newState [[-0.00361702  0.3600172   0.00718987 -0.50691651]]
state [[-0.00361702  0.3600172   0.00718987 -0.50691651]]
newState [[ 0.00358332  0.5550371  -0.00294846 -0.797325  ]]
state [[ 0.00358

state [[ 0.11127578  1.19805988 -0.08126175 -1.79638126]]
newState [[ 0.13523698  1.39399211 -0.11718938 -2.11317442]]
state [[ 0.13523698  1.39399211 -0.11718938 -2.11317442]]
newState [[ 0.16311682  1.59007386 -0.15945287 -2.43965459]]
state [[ 0.16311682  1.59007386 -0.15945287 -2.43965459]]
newState [[ 0.1949183   1.78616034 -0.20824596 -2.77673381]]
state [[ 0.1949183   1.78616034 -0.20824596 -2.77673381]]
newState [[ 0.23064151  1.98201553 -0.26378064 -3.12495219]]
Episode length: 18
Episode: 130
state [[-0.02682564  0.04218324 -0.02703774 -0.02593448]]
newState [[-0.02598197 -0.15254074 -0.02755643  0.25809661]]
state [[-0.02598197 -0.15254074 -0.02755643  0.25809661]]
newState [[-0.02903279  0.04296356 -0.0223945  -0.04314907]]
state [[-0.02903279  0.04296356 -0.0223945  -0.04314907]]
newState [[-0.02817352 -0.15183023 -0.02325748  0.2423849 ]]
state [[-0.02817352 -0.15183023 -0.02325748  0.2423849 ]]
newState [[-0.03121012  0.04361608 -0.01840978 -0.05754236]]
state [[-0.03121

state [[ 0.06046432  1.21091738 -0.05307085 -1.69800787]]
newState [[ 0.08468267  1.40660951 -0.08703101 -2.00672829]]
state [[ 0.08468267  1.40660951 -0.08703101 -2.00672829]]
newState [[ 0.11281486  1.21249524 -0.12716558 -1.74221374]]
state [[ 0.11281486  1.21249524 -0.12716558 -1.74221374]]
newState [[ 0.13706476  1.01902956 -0.16200985 -1.49164447]]
state [[ 0.13706476  1.01902956 -0.16200985 -1.49164447]]
newState [[ 0.15744536  1.21570994 -0.19184274 -1.83022459]]
state [[ 0.15744536  1.21570994 -0.19184274 -1.83022459]]
newState [[ 0.18175955  1.41236995 -0.22844723 -2.17585931]]
Episode length: 13
Episode: 148
state [[ 0.0335242   0.00464207  0.00396651 -0.00938499]]
newState [[ 0.03361704 -0.19053654  0.00377881  0.28454678]]
state [[ 0.03361704 -0.19053654  0.00377881  0.28454678]]
newState [[ 0.02980631  0.00453131  0.00946975 -0.00694194]]
state [[ 0.02980631  0.00453131  0.00946975 -0.00694194]]
newState [[ 0.02989693  0.19951618  0.00933091 -0.29662207]]
state [[ 0.02989

state [[ 0.03655619  0.18798142 -0.06569955 -0.39204439]]
newState [[ 0.04031582  0.38397123 -0.07354043 -0.70469663]]
state [[ 0.04031582  0.38397123 -0.07354043 -0.70469663]]
newState [[ 0.04799525  0.58003102 -0.08763437 -1.01959283]]
state [[ 0.04799525  0.58003102 -0.08763437 -1.01959283]]
newState [[ 0.05959587  0.77620463 -0.10802622 -1.33845558]]
state [[ 0.05959587  0.77620463 -0.10802622 -1.33845558]]
newState [[ 0.07511996  0.9725084  -0.13479533 -1.66289279]]
state [[ 0.07511996  0.9725084  -0.13479533 -1.66289279]]
newState [[ 0.09457013  1.16891809 -0.16805319 -1.99434475]]
state [[ 0.09457013  1.16891809 -0.16805319 -1.99434475]]
newState [[ 0.11794849  0.97590721 -0.20794008 -1.75808246]]
state [[ 0.11794849  0.97590721 -0.20794008 -1.75808246]]
newState [[ 0.13746663  1.17268991 -0.24310173 -2.10759272]]
Episode length: 14
Episode: 170
state [[ 0.03336996  0.03205442 -0.00909344  0.01016612]]
newState [[ 0.03401105  0.2273056  -0.00889011 -0.28537197]]
state [[ 0.03401

state [[ 0.01593109  0.41293738 -0.07301387 -0.67026319]]
newState [[ 0.02418983  0.60899443 -0.08641914 -0.98501223]]
state [[ 0.02418983  0.60899443 -0.08641914 -0.98501223]]
newState [[ 0.03636972  0.80516096 -0.10611938 -1.30353956]]
state [[ 0.03636972  0.80516096 -0.10611938 -1.30353956]]
newState [[ 0.05247294  1.00145669 -0.13219017 -1.62746737]]
state [[ 0.05247294  1.00145669 -0.13219017 -1.62746737]]
newState [[ 0.07250208  1.19786217 -0.16473952 -1.95825614]]
state [[ 0.07250208  1.19786217 -0.16473952 -1.95825614]]
newState [[ 0.09645932  1.39430409 -0.20390464 -2.29714425]]
state [[ 0.09645932  1.39430409 -0.20390464 -2.29714425]]
newState [[ 0.1243454   1.59063842 -0.24984753 -2.64507808]]
Episode length: 18
Episode: 193
state [[-0.01214337  0.02635757  0.02209467  0.04435086]]
newState [[-0.01161622  0.22115584  0.02298169 -0.24127992]]
state [[-0.01161622  0.22115584  0.02298169 -0.24127992]]
newState [[-0.0071931   0.41594209  0.01815609 -0.52662613]]
state [[-0.00719

state [[-0.01890662  0.01589906  0.01742989  0.02014597]]
newState [[-0.01858864  0.21076677  0.01783281 -0.26698706]]
state [[-0.01858864  0.21076677  0.01783281 -0.26698706]]
newState [[-0.0143733   0.40562973  0.01249306 -0.55399246]]
state [[-0.0143733   0.40562973  0.01249306 -0.55399246]]
newState [[-0.00626071  0.2103346   0.00141322 -0.25739976]]
state [[-0.00626071  0.2103346   0.00141322 -0.25739976]]
newState [[-0.00205402  0.0151925  -0.00373478  0.03572858]]
state [[-0.00205402  0.0151925  -0.00373478  0.03572858]]
newState [[-0.00175017  0.21036781 -0.00302021 -0.25813037]]
state [[-0.00175017  0.21036781 -0.00302021 -0.25813037]]
newState [[ 0.00245719  0.40553275 -0.00818282 -0.55176438]]
state [[ 0.00245719  0.40553275 -0.00818282 -0.55176438]]
newState [[ 0.01056785  0.21052667 -0.0192181  -0.26167077]]
state [[ 0.01056785  0.21052667 -0.0192181  -0.26167077]]
newState [[ 0.01477838  0.40591761 -0.02445152 -0.56035283]]
state [[ 0.01477838  0.40591761 -0.02445152 -0.5

state [[-0.02412131  0.21896798 -0.05765919 -0.38794508]]
newState [[-0.01974195  0.41485895 -0.06541809 -0.69823564]]
state [[-0.01974195  0.41485895 -0.06541809 -0.69823564]]
newState [[-0.01144477  0.22070213 -0.0793828  -0.42684257]]
state [[-0.01144477  0.22070213 -0.0793828  -0.42684257]]
newState [[-0.00703073  0.026789   -0.08791965 -0.16020291]]
state [[-0.00703073  0.026789   -0.08791965 -0.16020291]]
newState [[-0.00649495  0.22305244 -0.09112371 -0.47927608]]
state [[-0.00649495  0.22305244 -0.09112371 -0.47927608]]
newState [[-0.0020339   0.4193347  -0.10070923 -0.79923124]]
state [[-0.0020339   0.4193347  -0.10070923 -0.79923124]]
newState [[ 0.0063528   0.22572786 -0.11669386 -0.53985095]]
state [[ 0.0063528   0.22572786 -0.11669386 -0.53985095]]
newState [[ 0.01086735  0.42228016 -0.12749088 -0.86690445]]
state [[ 0.01086735  0.42228016 -0.12749088 -0.86690445]]
newState [[ 0.01931296  0.61888498 -0.14482897 -1.19679909]]
state [[ 0.01931296  0.61888498 -0.14482897 -1.1

state [[ 0.02269577  0.94031318 -0.13957077 -1.60744555]]
newState [[ 0.04150204  1.13678197 -0.17171968 -1.94018369]]
state [[ 0.04150204  1.13678197 -0.17171968 -1.94018369]]
newState [[ 0.06423768  1.33327115 -0.21052335 -2.28082047]]
Episode length: 11
Episode: 259
state [[-0.02529974  0.04871951  0.0422946  -0.00962914]]
newState [[-0.02432535 -0.14698269  0.04210202  0.29609253]]
state [[-0.02432535 -0.14698269  0.04210202  0.29609253]]
newState [[-0.027265    0.04751456  0.04802387  0.01697953]]
state [[-0.027265    0.04751456  0.04802387  0.01697953]]
newState [[-0.02631471  0.24191607  0.04836346 -0.26017295]]
state [[-0.02631471  0.24191607  0.04836346 -0.26017295]]
newState [[-0.02147639  0.43631545  0.04316    -0.53721774]]
state [[-0.02147639  0.43631545  0.04316    -0.53721774]]
newState [[-0.01275008  0.63080485  0.03241564 -0.81599506]]
state [[-0.01275008  0.63080485  0.03241564 -0.81599506]]
newState [[-1.33982085e-04  8.25468329e-01  1.60957429e-02 -1.09830836e+00]]


state [[ 0.02783108  0.2232761  -0.0359525  -0.39086264]]
newState [[ 0.03229661  0.41888937 -0.04376975 -0.69466068]]
state [[ 0.03229661  0.41888937 -0.04376975 -0.69466068]]
newState [[ 0.04067439  0.61459022 -0.05766296 -1.00079502]]
state [[ 0.04067439  0.61459022 -0.05766296 -1.00079502]]
newState [[ 0.0529662   0.42028432 -0.07767886 -0.7267641 ]]
state [[ 0.0529662   0.42028432 -0.07767886 -0.7267641 ]]
newState [[ 0.06137188  0.61638942 -0.09221414 -1.04284935]]
state [[ 0.06137188  0.61638942 -0.09221414 -1.04284935]]
newState [[ 0.07369967  0.81260693 -0.11307113 -1.36299766]]
state [[ 0.07369967  0.81260693 -0.11307113 -1.36299766]]
newState [[ 0.08995181  1.00894931 -0.14033108 -1.68880266]]
state [[ 0.08995181  1.00894931 -0.14033108 -1.68880266]]
newState [[ 0.1101308   0.81570104 -0.17410714 -1.44290184]]
state [[ 0.1101308   0.81570104 -0.17410714 -1.44290184]]
newState [[ 0.12644482  1.01248584 -0.20296517 -1.78454571]]
state [[ 0.12644482  1.01248584 -0.20296517 -1.7

state [[ 0.016868    0.99120111 -0.04343248 -1.42508623]]
newState [[ 0.03669202  1.18683215 -0.07193421 -1.73102119]]
state [[ 0.03669202  1.18683215 -0.07193421 -1.73102119]]
newState [[ 0.06042867  0.99260159 -0.10655463 -1.46155924]]
state [[ 0.06042867  0.99260159 -0.10655463 -1.46155924]]
newState [[ 0.0802807   1.18885608 -0.13578581 -1.78553918]]
state [[ 0.0802807   1.18885608 -0.13578581 -1.78553918]]
newState [[ 0.10405782  0.99549586 -0.1714966  -1.53796706]]
state [[ 0.10405782  0.99549586 -0.1714966  -1.53796706]]
newState [[ 0.12396774  1.19221635 -0.20225594 -1.87889231]]
state [[ 0.12396774  1.19221635 -0.20225594 -1.87889231]]
newState [[ 0.14781206  1.38888793 -0.23983379 -2.22694488]]
Episode length: 11
Episode: 303
state [[ 0.03605693  0.04455293 -0.01806687  0.01095639]]
newState [[ 0.03694799  0.23992926 -0.01784774 -0.28737165]]
state [[ 0.03694799  0.23992926 -0.01784774 -0.28737165]]
newState [[ 0.04174658  0.43530113 -0.02359518 -0.58562974]]
state [[ 0.04174

state [[-0.00081018  0.42127478 -0.03899871 -0.58920976]]
newState [[ 0.00761532  0.61692049 -0.0507829  -0.89391791]]
state [[ 0.00761532  0.61692049 -0.0507829  -0.89391791]]
newState [[ 0.01995373  0.42252267 -0.06866126 -0.61762085]]
state [[ 0.01995373  0.42252267 -0.06866126 -0.61762085]]
newState [[ 0.02840418  0.61853319 -0.08101368 -0.93111441]]
state [[ 0.02840418  0.61853319 -0.08101368 -0.93111441]]
newState [[ 0.04077485  0.81464949 -0.09963597 -1.248116  ]]
state [[ 0.04077485  0.81464949 -0.09963597 -1.248116  ]]
newState [[ 0.05706784  1.01089767 -0.12459829 -1.57027285]]
state [[ 0.05706784  1.01089767 -0.12459829 -1.57027285]]
newState [[ 0.07728579  1.20726723 -0.15600374 -1.89908089]]
state [[ 0.07728579  1.20726723 -0.15600374 -1.89908089]]
newState [[ 0.10143113  1.40369673 -0.19398536 -2.23582629]]
state [[ 0.10143113  1.40369673 -0.19398536 -2.23582629]]
newState [[ 0.12950507  1.60005739 -0.23870189 -2.58151748]]
Episode length: 10
Episode: 323
state [[ 0.01192

state [[-0.00652261 -0.217554   -0.02264938  0.29290106]]
newState [[-0.01087369 -0.02211656 -0.01679136 -0.00683825]]
state [[-0.01087369 -0.02211656 -0.01679136 -0.00683825]]
newState [[-0.01131602 -0.21699373 -0.01692812  0.28049986]]
state [[-0.01131602 -0.21699373 -0.01692812  0.28049986]]
newState [[-0.01565589 -0.02163445 -0.01131813 -0.01747371]]
state [[-0.01565589 -0.02163445 -0.01131813 -0.01747371]]
newState [[-0.01608858 -0.21659227 -0.0116676   0.27161684]]
state [[-0.01608858 -0.21659227 -0.0116676   0.27161684]]
newState [[-0.02042043 -0.4115458  -0.00623526  0.56059704]]
state [[-0.02042043 -0.4115458  -0.00623526  0.56059704]]
newState [[-0.02865134 -0.60657969  0.00497668  0.85130903]]
state [[-0.02865134 -0.60657969  0.00497668  0.85130903]]
newState [[-0.04078294 -0.80176914  0.02200286  1.14555272]]
state [[-0.04078294 -0.80176914  0.02200286  1.14555272]]
newState [[-0.05681832 -0.99717145  0.04491391  1.44505356]]
state [[-0.05681832 -0.99717145  0.04491391  1.4

ValueError: Error when checking target: expected dense_120 to have 2 dimensions, but got array with shape ()

In [322]:
solver.run_q_learning(n_episodes=1000)

Episode: 1
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 2
Episode length: 18
[0. 0. 0. 0. 0.]
Episode: 3
Episode length: 16
[0. 0. 0. 0. 0.]
Episode: 4
Episode length: 13
[0. 0. 0. 0. 0.]
Episode: 5
Episode length: 11
[0. 0. 0. 0. 0.]
Episode: 6
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 7
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 8
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 9
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 10
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 11
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 12
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 13
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 14
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 15
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 16
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 17
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 18
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 19
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 20
Episode length: 12
[0. 0. 0. 0. 0.]
Episode: 21
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 

Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 325
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 326
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 327
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 328
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 329
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 330
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 331
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 332
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 333
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 334
Episode length: 11
[0. 0. 0. 0. 0.]
Episode: 335
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 336
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 337
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 338
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 339
Episode length: 11
[0. 0. 0. 0. 0.]
Episode: 340
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 341
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 342
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 343
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 344
Episode length: 9
[0. 0. 0. 0. 0.

Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 502
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 503
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 504
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 505
Episode length: 11
[0. 0. 0. 0. 0.]
Episode: 506
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 507
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 508
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 509
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 510
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 511
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 512
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 513
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 514
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 515
Episode length: 10
[0. 0. 0. 0. 0.]
Episode: 516
Episode length: 8
[0. 0. 0. 0. 0.]
Episode: 517
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 518
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 519
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 520
Episode length: 9
[0. 0. 0. 0. 0.]
Episode: 521
Episode length: 9
[0. 0. 0. 0

KeyboardInterrupt: 

In [310]:
solver.run_episode(render=True, exposition=True)

Episode length: 9


In [306]:
np.matrix([list(np.array([1, 2])) + [0],
           list(np.array([1, 2])) + [1]]).shape

(2, 3)

In [99]:
list(np.array([1, 2])) + [0]

[1, 2, 0]

In [14]:
env.action_space.n

2

In [15]:
solver.run_q_learning(1000)

Episode: 0
Episode length: 10
Episode: 1
Episode length: 9
Episode: 2
Episode length: 13
Episode: 3
Episode length: 33
Episode: 4
Episode length: 21
Episode: 5
Episode length: 18
Episode: 6
Episode length: 10
Episode: 7
Episode length: 18
Episode: 8
Episode length: 12
Episode: 9
Episode length: 20
Episode: 10
Episode length: 17
Episode: 11
Episode length: 37
Episode: 12
Episode length: 31
Episode: 13
Episode length: 12
Episode: 14
Episode length: 13
Episode: 15
Episode length: 15
Episode: 16
Episode length: 12
Episode: 17
Episode length: 12
Episode: 18
Episode length: 13
Episode: 19
Episode length: 10
Episode: 20
Episode length: 11
Episode: 21
Episode length: 17
Episode: 22
Episode length: 45
Episode: 23
Episode length: 15
Episode: 24
Episode length: 13
Episode: 25
Episode length: 40
Episode: 26
Episode length: 14
Episode: 27
Episode length: 26
Episode: 28
Episode length: 28
Episode: 29
Episode length: 9
Episode: 30
Episode length: 35
Episode: 31
Episode length: 11
Episode: 32
Episode 

Episode length: 17
Episode: 273
Episode length: 18
Episode: 274
Episode length: 16
Episode: 275
Episode length: 16
Episode: 276
Episode length: 15
Episode: 277
Episode length: 16
Episode: 278
Episode length: 29
Episode: 279
Episode length: 13
Episode: 280
Episode length: 42
Episode: 281
Episode length: 25
Episode: 282
Episode length: 25
Episode: 283
Episode length: 42
Episode: 284
Episode length: 26
Episode: 285
Episode length: 18
Episode: 286
Episode length: 12
Episode: 287
Episode length: 67
Episode: 288
Episode length: 49
Episode: 289
Episode length: 22
Episode: 290
Episode length: 15
Episode: 291
Episode length: 37
Episode: 292
Episode length: 12
Episode: 293
Episode length: 14
Episode: 294
Episode length: 25
Episode: 295
Episode length: 30
Episode: 296
Episode length: 15
Episode: 297
Episode length: 13
Episode: 298
Episode length: 16
Episode: 299
Episode length: 33
Episode: 300
Episode length: 37
Episode: 301
Episode length: 30
Episode: 302
Episode length: 8
Episode: 303
Episode l

Episode length: 26
Episode: 547
Episode length: 13
Episode: 548
Episode length: 20
Episode: 549
Episode length: 13
Episode: 550
Episode length: 12
Episode: 551
Episode length: 16
Episode: 552
Episode length: 21
Episode: 553
Episode length: 44
Episode: 554
Episode length: 26
Episode: 555
Episode length: 23
Episode: 556
Episode length: 46
Episode: 557
Episode length: 22
Episode: 558
Episode length: 14
Episode: 559
Episode length: 15
Episode: 560
Episode length: 38
Episode: 561
Episode length: 20
Episode: 562
Episode length: 9
Episode: 563
Episode length: 13
Episode: 564
Episode length: 22
Episode: 565
Episode length: 26
Episode: 566
Episode length: 16
Episode: 567
Episode length: 12
Episode: 568
Episode length: 16
Episode: 569
Episode length: 15
Episode: 570
Episode length: 38
Episode: 571
Episode length: 20
Episode: 572
Episode length: 25
Episode: 573
Episode length: 17
Episode: 574
Episode length: 25
Episode: 575
Episode length: 12
Episode: 576
Episode length: 20
Episode: 577
Episode l

Episode length: 14
Episode: 810
Episode length: 12
Episode: 811
Episode length: 12
Episode: 812
Episode length: 12
Episode: 813
Episode length: 12
Episode: 814
Episode length: 21
Episode: 815
Episode length: 14
Episode: 816
Episode length: 21
Episode: 817
Episode length: 10
Episode: 818
Episode length: 32
Episode: 819
Episode length: 22
Episode: 820
Episode length: 11
Episode: 821
Episode length: 20
Episode: 822
Episode length: 27
Episode: 823
Episode length: 13
Episode: 824
Episode length: 29
Episode: 825
Episode length: 36
Episode: 826
Episode length: 14
Episode: 827
Episode length: 18
Episode: 828
Episode length: 13
Episode: 829
Episode length: 16
Episode: 830
Episode length: 44
Episode: 831
Episode length: 15
Episode: 832
Episode length: 12
Episode: 833
Episode length: 11
Episode: 834
Episode length: 45
Episode: 835
Episode length: 10
Episode: 836
Episode length: 36
Episode: 837
Episode length: 40
Episode: 838
Episode length: 13
Episode: 839
Episode length: 31
Episode: 840
Episode 

Episode length: 8


In [25]:
tuple(solver.discretize(env.reset(), env.observation_space))

(4, 6, 3, 6)

In [27]:
solver.Q[tuple(solver.discretize(env.reset(), env.observation_space))]

array([0., 0.])

In [161]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression()
reg.coef_ = np.zeros(2)
reg.intercept_ = 5
#reg.fit(X, y)
reg.predict(np.array([[3, 5]]))

array([5.])

In [138]:
reg.coef_

array([1., 2.])

In [160]:
reg.intercept_

3.0000000000000018

In [67]:
X = np.array([[20, 20]])
y = y[0]

In [69]:
reg.fit(X, y)

TypeError: Singleton array array(6) cannot be considered a valid collection.