![Q-learning](qlearning.png)

In [1]:
import gym

In [2]:
env = gym.make('CartPole-v1')
env.reset()

array([ 0.01869866, -0.00817757,  0.04722285, -0.0291307 ])

In [3]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.01396347 -0.00391847  0.0420014   0.0315317 ]
[ 0.0138851  -0.19961678  0.04263203  0.33716507]
[ 0.00989277 -0.39531866  0.04937533  0.64298118]
[ 0.0019864  -0.59109278  0.06223496  0.95079491]
[-0.00983546 -0.78699466  0.08125085  1.26236412]
[-0.02557535 -0.98305607  0.10649814  1.57934748]
[-0.04523647 -1.17927294  0.13808509  1.90325657]
[-0.06882193 -1.37559154  0.17615022  2.23539958]
Episode finished after 8 timesteps
[-0.03754457  0.03901411 -0.03330312 -0.01867695]
[-0.03676429  0.23459745 -0.03367666 -0.32167859]
[-0.03207234  0.03997085 -0.04011023 -0.03980329]
[-0.03127292 -0.15455365 -0.0409063   0.23995954]
[-0.03436399 -0.3490681  -0.03610711  0.51946402]
[-0.04134536 -0.54366362 -0.02571783  0.80055387]
[-0.05221863 -0.73842356 -0.00970675  1.08503696]
[-0.0669871  -0.93341611  0.01199399  1.37465827]
[-0.08565542 -0.7384461   0.03948715  1.08575043]
[-0.10042434 -0.54386665  0.06120216  0.80571498]
[-0.11130168 -0.34963466  0.07731646  0.53289469]
[-0.11829437 -0

[ 0.00234217  0.16980515 -0.15294784 -0.59576857]
[ 0.00573828 -0.02288285 -0.16486322 -0.3549022 ]
[ 0.00528062  0.17415238 -0.17196126 -0.69469811]
[ 0.00876367  0.37118947 -0.18585522 -1.03620242]
[ 0.01618746  0.56823002 -0.20657927 -1.38100067]
Episode finished after 64 timesteps
[ 0.03750048  0.03675402 -0.04310279 -0.00567288]
[ 0.03823556  0.23246678 -0.04321625 -0.31163765]
[ 0.04288489  0.42817692 -0.049449   -0.61763039]
[ 0.05144843  0.23377934 -0.06180161 -0.34092254]
[ 0.05612402  0.42972367 -0.06862006 -0.65243602]
[ 0.06471849  0.23562104 -0.08166878 -0.38212575]
[ 0.06943091  0.43180189 -0.08931129 -0.69940015]
[ 0.07806695  0.23802422 -0.1032993  -0.43611476]
[ 0.08282743  0.04450464 -0.11202159 -0.17769877]
[ 0.08371753  0.2410366  -0.11557557 -0.50351446]
[ 0.08853826  0.04771703 -0.12564586 -0.24937331]
[ 0.0894926   0.24438843 -0.13063332 -0.57889761]
[ 0.09438037  0.05131584 -0.14221128 -0.33005336]
[ 0.09540668 -0.1415256  -0.14881234 -0.08538064]
[ 0.09257617  

[-0.18519469 -0.44403849  0.20867516  0.92286644]
Episode finished after 17 timesteps
[ 0.02695256 -0.0426342   0.01351325 -0.01955836]
[ 0.02609987 -0.23794731  0.01312208  0.27735734]
[ 0.02134093 -0.43325398  0.01866923  0.57414991]
[ 0.01267585 -0.62863263  0.03015223  0.87265524]
[ 1.03194259e-04 -8.24151347e-01  4.76053299e-02  1.17466342e+00]
[-0.01637983 -0.62967926  0.0710986   0.89727645]
[-0.02897342 -0.4355894   0.08904413  0.62776258]
[-0.03768521 -0.63183389  0.10159938  0.94710749]
[-0.05032188 -0.82816638  0.12054153  1.26990641]
[-0.06688521 -1.02460334  0.14593966  1.59777718]
[-0.08737728 -0.83148143  0.1778952   1.35392784]
[-0.10400691 -0.63898187  0.20497376  1.12176121]
Episode finished after 12 timesteps
[ 0.04641812 -0.04732364 -0.03008149 -0.00687968]
[ 0.04547165 -0.24200155 -0.03021908  0.27616245]
[ 0.04063162 -0.43667962 -0.02469583  0.55916318]
[ 0.03189803 -0.2412199  -0.01351257  0.25880316]
[ 0.02707363 -0.43614636 -0.0083365   0.54719358]
[ 0.0183507 

In [4]:
print(env.action_space)
# 0: 1 unit of force in left direction
# 1: 1 unit of force in right direction

Discrete(2)


In [5]:
print(env.observation_space)
# 0: Cart position
# 1: Cart velocity
# 2: Pole angle
# 3: Pole velocity at tip

Box(4,)


# Cartpole domain

In [8]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [9]:
env.observation_space.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

The input space is 4 dimensional and continuous.
* Cart position: $x: \in [-4.8, 4.8]$
* Cart velocity: $x' \in [-3.4*10^{38}, 3.4*10^{38}]$
* Angle: $\theta \in [-0.42, 0.42]$
* Angle velocity: $\theta' \in [-3.4*10^{38}, 3.4*10^{38}]$

# Q-learning parameters
* $\alpha$: Learning rate - Used to smooth the updates and make them less radical, which prevents errors caused by noise.
* $\epsilon$: Exploration rate - Regulates between explotation and exploration. Instead of picking the best action in a state, which a probability of $\epsilon$ a random action is picked. This should prevent the algorithm from getting stuck at a local minima (e.g. if a bad choice was made in the beginning, without $\epsilon$ the agent would never discover any other, potentially better, path.
* $\gamma$: Discount factor - Used to penalize the agent if it takes long to reach its goal. However in this case we set gamma to 1 since it is our goal to survive as long as possible.

In [71]:
class QSolver():
    def __init__(self, env, eps, alpha, gamma):
        self.env = env
        self.eps = eps
        self.alpha = alpha
        self.gamma = gamma
        
    def greedy_action():
        raise NotImplementedError
        
    def epsilon_greedy(self, state):
        if np.random.random() <= self.eps:
            return self.greedy_action(state)
        return self.env.action_space.sample()
    
    def step(self, action):
        return self.env.step(action)
    
    def update_Q(self, state, action, newReward, newState):
        raise NotImplementedError
    
    def run_episode(self, render=False, exposition=False):
        state = env.reset()
        
        t = 0
        while True:
            t += 1
            
            if render:
                env.render()
                
            if exposition:
                action = self.greedy_action(state)
            else:
                action = self.epsilon_greedy(state)
                
            newState, newReward, done, info = env.step(action)
            
            if not exposition:
                self.update_Q(state, action, newReward, newState)
            state = newState

            if done:
                print(f"Episode length: {t}")
                break
                
        env.close()
        
    def run_q_learning(self, n_episodes, render=False):
        for t in range(n_episodes):
            print(f"Episode: {t}")
            self.run_episode()
            
            self.eps = 1/(t+1)

In [72]:
class DiscreteQSolver(QSolver):
    def __init__(self, env, eps, alpha, gamma, bucket_sizes=(7, 13, 7, 13)):
        QSolver.__init__(self, env, eps, alpha, gamma)
        self.bucket_sizes = bucket_sizes
        self.Q = np.zeros(bucket_sizes + (self.env.action_space.n,))
        
    def greedy_action(self, state):
        state_discrete = self.discretize(state, self.env.observation_space)
        return np.argmax(self.Q[tuple(state_discrete)])
    
    def step(self, action):
        observation, reward, done, info = self.env.step(action)
        return discretize(observation), reward, done, info
    
    def update_Q(self, state, action, newReward, newState):
        state_discrete = self.discretize(state.copy(), self.env.observation_space)
        newState_discrete = self.discretize(newState.copy(), self.env.observation_space)
        
        greedy_action = self.greedy_action(newState_discrete)
        q_greedy_action = self.Q[tuple(state_discrete)][greedy_action]
        self.Q[tuple(state_discrete)][action] + self.alpha * (newReward + self.gamma * q_greedy_action - self.Q[tuple(state_discrete)][action])     
        
    def discretize(self, obs, obs_space):
        bucket_arrays = [np.linspace(obs_space.low[i], obs_space.high[i], self.bucket_sizes[i]) for i, x in enumerate(obs)]
        state_space = [np.digitize(obs[i], bucket_arrays[i]) for i, x in enumerate(obs)]
        return np.array(state_space).ravel()-1

In [12]:
import numpy as np

In [99]:
discretize(env.reset(), env.observation_space)

array([3, 7, 4, 7])

In [73]:
eps = 0.9
alpha = 0.05
gamma = 0.5
solver = DiscreteQSolver(env, eps, alpha, gamma)

In [102]:
solver.Q.shape

(7, 13, 7, 13, 2)

In [97]:
solver.step()

TypeError: step() missing 1 required positional argument: 'action'

In [93]:
env.action_space.n

2

In [74]:
solver.run_q_learning(1000)

Episode: 0
Episode length: 9
Episode: 1
Episode length: 9
Episode: 2
Episode length: 9
Episode: 3
Episode length: 15
Episode: 4
Episode length: 15
Episode: 5
Episode length: 44
Episode: 6
Episode length: 29
Episode: 7
Episode length: 47
Episode: 8
Episode length: 39
Episode: 9
Episode length: 15
Episode: 10
Episode length: 27
Episode: 11
Episode length: 19
Episode: 12
Episode length: 19
Episode: 13
Episode length: 12
Episode: 14
Episode length: 10
Episode: 15
Episode length: 27
Episode: 16
Episode length: 25
Episode: 17
Episode length: 22
Episode: 18
Episode length: 10
Episode: 19
Episode length: 17
Episode: 20
Episode length: 50
Episode: 21
Episode length: 15
Episode: 22
Episode length: 16
Episode: 23
Episode length: 19
Episode: 24
Episode length: 28
Episode: 25
Episode length: 30
Episode: 26
Episode length: 31
Episode: 27
Episode length: 18
Episode: 28
Episode length: 23
Episode: 29
Episode length: 21
Episode: 30
Episode length: 15
Episode: 31
Episode length: 29
Episode: 32
Episode l

Episode length: 27
Episode: 260
Episode length: 17
Episode: 261
Episode length: 10
Episode: 262
Episode length: 16
Episode: 263
Episode length: 13
Episode: 264
Episode length: 43
Episode: 265
Episode length: 27
Episode: 266
Episode length: 27
Episode: 267
Episode length: 17
Episode: 268
Episode length: 13
Episode: 269
Episode length: 17
Episode: 270
Episode length: 27
Episode: 271
Episode length: 13
Episode: 272
Episode length: 19
Episode: 273
Episode length: 11
Episode: 274
Episode length: 14
Episode: 275
Episode length: 21
Episode: 276
Episode length: 14
Episode: 277
Episode length: 37
Episode: 278
Episode length: 16
Episode: 279
Episode length: 17
Episode: 280
Episode length: 16
Episode: 281
Episode length: 42
Episode: 282
Episode length: 18
Episode: 283
Episode length: 25
Episode: 284
Episode length: 35
Episode: 285
Episode length: 8
Episode: 286
Episode length: 14
Episode: 287
Episode length: 27
Episode: 288
Episode length: 22
Episode: 289
Episode length: 28
Episode: 290
Episode l

Episode length: 14
Episode: 532
Episode length: 21
Episode: 533
Episode length: 29
Episode: 534
Episode length: 13
Episode: 535
Episode length: 34
Episode: 536
Episode length: 22
Episode: 537
Episode length: 37
Episode: 538
Episode length: 19
Episode: 539
Episode length: 58
Episode: 540
Episode length: 25
Episode: 541
Episode length: 10
Episode: 542
Episode length: 18
Episode: 543
Episode length: 13
Episode: 544
Episode length: 15
Episode: 545
Episode length: 14
Episode: 546
Episode length: 33
Episode: 547
Episode length: 33
Episode: 548
Episode length: 55
Episode: 549
Episode length: 35
Episode: 550
Episode length: 21
Episode: 551
Episode length: 45
Episode: 552
Episode length: 11
Episode: 553
Episode length: 19
Episode: 554
Episode length: 22
Episode: 555
Episode length: 16
Episode: 556
Episode length: 37
Episode: 557
Episode length: 11
Episode: 558
Episode length: 10
Episode: 559
Episode length: 24
Episode: 560
Episode length: 29
Episode: 561
Episode length: 10
Episode: 562
Episode 

Episode length: 19
Episode: 791
Episode length: 24
Episode: 792
Episode length: 15
Episode: 793
Episode length: 21
Episode: 794
Episode length: 26
Episode: 795
Episode length: 24
Episode: 796
Episode length: 24
Episode: 797
Episode length: 17
Episode: 798
Episode length: 35
Episode: 799
Episode length: 33
Episode: 800
Episode length: 33
Episode: 801
Episode length: 25
Episode: 802
Episode length: 19
Episode: 803
Episode length: 8
Episode: 804
Episode length: 15
Episode: 805
Episode length: 19
Episode: 806
Episode length: 43
Episode: 807
Episode length: 72
Episode: 808
Episode length: 12
Episode: 809
Episode length: 20
Episode: 810
Episode length: 10
Episode: 811
Episode length: 37
Episode: 812
Episode length: 15
Episode: 813
Episode length: 17
Episode: 814
Episode length: 30
Episode: 815
Episode length: 25
Episode: 816
Episode length: 35
Episode: 817
Episode length: 23
Episode: 818
Episode length: 22
Episode: 819
Episode length: 26
Episode: 820
Episode length: 27
Episode: 821
Episode l

In [78]:
solver.run_episode(render=True, exposition=True)

Episode length: 9


In [25]:
tuple(solver.discretize(env.reset(), env.observation_space))

(4, 6, 3, 6)

In [27]:
solver.Q[tuple(solver.discretize(env.reset(), env.observation_space))]

array([0., 0.])