In [1]:
import gym
import math

In [4]:
def discretize(obs):
    """
    """
    upper_bounds = [env.observation_space.high[0], 0.5, env.observation_space.high[2], math.radians(50)]
    lower_bounds = [env.observation_space.low[0], 0.5, env.observation_space.low[2], math.radians(50)]
    ratios = [(obs[i] + abs(lower_bounds[i])) / (upper_bounds[i] - lower_bounds[i]) for i in range(len(obs))]
    new_obs = [int(round(buckets[i] -1)) + ratios[i] for i in range(len(obs))]
    new_obs = [min(buckets[i] - 1, max(0, new_obs[i])) for i in range(len(obs))]
    return tuple(new_obs)


In [8]:
obs = observation
buckets = (1, 1, 6, 12,)

In [9]:
upper_bounds = [env.observation_space.high[0], 0.5, env.observation_space.high[2], math.radians(50)]
lower_bounds = [env.observation_space.low[0], 0.5, env.observation_space.low[2], math.radians(50)]

In [ ]:
ratios = [(obs[i] + abs(lower_bounds[i])) / (upper_bounds[i] - lower_bounds[i]) for i in range(len(obs))]
new_obs = [int(round(buckets[i] -1)) + ratios[i] for i in range(len(obs))]
new_obs = [min(buckets[i] - 1, max(0, new_obs[i])) for i in range(len(obs))]

In [12]:
obs

array([ 0.04500629,  0.38062257, -0.23317105, -1.22258429])

In [11]:
new_obs

[0, 0, 5, 0]

In [ ]:
theta ∈ [0, 6] ⊂ ℕ

In [2]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print('~~', env.observation_space.high)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[-0.02035192  0.01546082 -0.02239354  0.01167808]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.0200427   0.21089665 -0.02215998 -0.28798531]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.01582477  0.40632749 -0.02791969 -0.5875741 ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.00769822  0.60182909 -0.03967117 -0.88891954]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.00433837  0.7974663  -0.05744956 -1.19380472]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.02028769  0.99328328 -0.08132566 -1.50392649]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.04015336  0.79923696 -0.11140419 -1.23770243]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.0561381   0.99559969 -0.13615823 -1.56310575]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.07605009  0.80234338 -0.16742035 -1.31581118]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[

[-0.08626518 -0.43120554  0.07492612  0.66349811]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.09488929 -0.62728548  0.08819608  0.9788005 ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.107435   -0.43344955  0.10777209  0.71507274]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.11610399 -0.2399714   0.12207355  0.458163  ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.12090342 -0.43658846  0.13123681  0.78669438]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.12963519 -0.63324558  0.14697069  1.11761638]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.1423001  -0.82995795  0.16932302  1.45255787]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.15889926 -0.63727169  0.19837418  1.21720529]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
Episode finished after 14 timesteps
[-0.04821309 -0.01577358 -0.0120354  -0.03817752]
~~ [4.8000002e+00 3.402823

[ 0.05683315  1.3788837  -0.1509801  -1.98039491]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.08441083  1.57523765 -0.19058799 -2.31579499]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
Episode finished after 35 timesteps
[ 0.00546493 -0.02989872  0.02654985  0.03204735]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.00486695  0.16483263  0.0271908  -0.252142  ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.00816361  0.35955597  0.02214796 -0.53612593]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01535472  0.16412972  0.01142544 -0.23654747]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01863732  0.35908658  0.00669449 -0.52560469]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.02581905  0.55411369 -0.00381761 -0.81617063]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.03690132  0.74928771 -0.02014102 -1.11005189]
~~ [4.8000002e+00 3.402823

[-0.05350828 -0.20167366  0.04267817  0.3099299 ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.05754176 -0.00718494  0.04887677  0.03100604]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.05768545 -0.2029725   0.04949689  0.3387007 ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.0617449  -0.39876254  0.0562709   0.64657223]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.06972015 -0.20446793  0.06920235  0.37212651]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.07380951 -0.40050125  0.07664488  0.68580194]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.08181954 -0.59659884  0.09036092  1.00159631]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.09375152 -0.40279291  0.11039284  0.73860342]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.10180737 -0.20935448  0.12516491  0.4826016 ]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[

[-0.03789856 -0.36823726  0.12031751  0.73734783]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.0452633  -0.56479727  0.13506447  1.06534438]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.05655925 -0.76142281  0.15637135  1.39718491]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.07178771 -0.56855274  0.18431505  1.15719572]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.08315876 -0.37624788  0.20745897  0.92750663]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
Episode finished after 15 timesteps
[-0.01477061  0.00569458 -0.00922423  0.04598697]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.01465672 -0.1892939  -0.00830449  0.33574536]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.0184426  -0.38429668 -0.00158958  0.62579796]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-0.02612853 -0.57939641  0.01092638  0.91797984]
~~ [4.8000002e+00 3.402823

[ 0.00367136  0.35811334 -0.08582986 -0.69834015]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01083363  0.16427972 -0.09979667 -0.43386302]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01411923  0.36066249 -0.10847393 -0.75626304]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.02133248  0.16718955 -0.12359919 -0.49958817]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.02467627 -0.02599298 -0.13359095 -0.24827067]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.02415641 -0.21897925 -0.13855636 -0.00052955]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01977682 -0.02217023 -0.13856696 -0.33351924]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.01933342  0.17462392 -0.14523734 -0.66648949]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[ 0.0228259  -0.01821146 -0.15856713 -0.42283162]
~~ [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[

In [ ]:
import gym
import numpy as np
import math
from collections import deque

class QCartPoleSolver():
    def __init__(self, buckets=(1, 1, 6, 12,), n_episodes=1000, n_win_ticks=195, min_alpha=0.1, min_epsilon=0.1, gamma=1.0, ada_divisor=25, max_env_steps=None, quiet=False, monitor=False):
        self.buckets = buckets # down-scaling feature space to discrete range
        self.n_episodes = n_episodes # training episodes 
        self.n_win_ticks = n_win_ticks # average ticks over 100 episodes required for win
        self.min_alpha = min_alpha # learning rate
        self.min_epsilon = min_epsilon # exploration rate
        self.gamma = gamma # discount factor
        self.ada_divisor = ada_divisor # only for development purposes
        self.quiet = quiet

        self.env = gym.make('CartPole-v0')
        if max_env_steps is not None: self.env._max_episode_steps = max_env_steps
        if monitor: self.env = gym.wrappers.Monitor(self.env, 'tmp/cartpole-1', force=True) # record results for upload

        self.Q = np.zeros(self.buckets + (self.env.action_space.n,))

    def discretize(self, obs):
        upper_bounds = [self.env.observation_space.high[0], 0.5, self.env.observation_space.high[2], math.radians(50)]
        lower_bounds = [self.env.observation_space.low[0], -0.5, self.env.observation_space.low[2], -math.radians(50)]
        ratios = [(obs[i] + abs(lower_bounds[i])) / (upper_bounds[i] - lower_bounds[i]) for i in range(len(obs))]
        new_obs = [int(round((self.buckets[i] - 1) * ratios[i])) for i in range(len(obs))]
        new_obs = [min(self.buckets[i] - 1, max(0, new_obs[i])) for i in range(len(obs))]
        return tuple(new_obs)

    def choose_action(self, state, epsilon):
        return self.env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(self.Q[state])

    def update_q(self, state_old, action, reward, state_new, alpha):
        self.Q[state_old][action] += alpha * (reward + self.gamma * np.max(self.Q[state_new]) - self.Q[state_old][action])

    def get_epsilon(self, t):
        return max(self.min_epsilon, min(1, 1.0 - math.log10((t + 1) / self.ada_divisor)))

    def get_alpha(self, t):
        return max(self.min_alpha, min(1.0, 1.0 - math.log10((t + 1) / self.ada_divisor)))

    def run(self):
        scores = deque(maxlen=100)

        for e in range(self.n_episodes):
            current_state = self.discretize(self.env.reset())

            alpha = self.get_alpha(e)
            epsilon = self.get_epsilon(e)
            done = False
            i = 0

            while not done:
                # self.env.render()
                action = self.choose_action(current_state, epsilon)
                obs, reward, done, _ = self.env.step(action)
                new_state = self.discretize(obs)
                self.update_q(current_state, action, reward, new_state, alpha)
                current_state = new_state
                i += 1

            scores.append(i)
            mean_score = np.mean(scores)
            if mean_score >= self.n_win_ticks and e >= 100:
                if not self.quiet: print('Ran {} episodes. Solved after {} trials ✔'.format(e, e - 100))
                return e - 100
            if e % 100 == 0 and not self.quiet:
                print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))

        if not self.quiet: print('Did not solve after {} episodes 😞'.format(e))
        return e


In [1]:
import numpy as np

In [2]:
a = np.matrix('1 2; 3 4')

In [3]:
a

matrix([[1, 2],
        [3, 4]])

In [10]:
a[(1)].shape

(1, 2)